version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017" # Map the container port to the host
    volumes:
      - mongo-data:/data/db # Persist MongoDB data locally
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zypsie

volumes:
  mongo-data:
